
.PHONY: all setup

# The first rule in a Makefile is the one executed by default ("make"). It
# should always be the "all" rule, so that "make" and "make all" are identical.
all:
	echo "Install lmacros autocompletion for TeXstudio by running 'make setup'."

# Setup the LaTeX-package and everything for compilation
setup:
	# Link autocomplete file into TeXstudio
	if [ -d ${HOME}/.config/texstudio/completion/ ]; then \
		rm -f ${HOME}/.config/texstudio/completion/autogenerated/lmacros.cwl; \
		ln -f -s ${PWD}/lmacros.cwl ${HOME}/.config/texstudio/completion/user/lmacros.cwl; \
		echo "Link created! Restart TeXstudio for the changes to take effect."; \
	fi
